acquaintance_0={
    'first_name':'lai',
    'last_name':'shuming',
    'age':'24',
    'city':'dongguan',
}
print(acquaintance_0['first_name'])
print(acquaintance_0['last_name'])
print(acquaintance_0['age'])
print(acquaintance_0['city'])
