guests=['lindengliang','fangyuheng','zhangxiaofeng','tangweishun']
print(guests[0]+", I want to invite to dinner")
print(guests[1]+", I want to invite to dinner")
print(guests[2]+", I want to invite to dinner")
print(guests[3]+", I want to invite to dinner")
guest_absent='lindengliang'
guests.remove(guest_absent)
print(guest_absent+", he don't come to the dinner")
guests.insert(0,'laixiaojun')
print(guests[0]+", I want to invite to dinner")
print(guests[1]+", I want to invite to dinner")
print(guests[2]+", I want to invite to dinner")
print(guests[3]+", I want to invite to dinner")
print("I find a bigger table")
guests.insert(0,'jiangjunxin')
guests.insert(3,'pengwenlei')
guests.append('chengengjian')
print(guests[0]+', I want to invite you to dinner')
print(guests[1]+", I want to invite you to dinner")
print(guests[2]+", I want to invite you to dinner")
print(guests[3]+", I want to invite you to dinner")
print(guests[4]+", I want to invite you to dinner")
print(guests[5]+", I want to invite you to dinner")
print("I only invite two people to dinner")
print("Sorry, "+guests.pop()+", I can't invite you to dinner")
print("Sorry, "+guests.pop()+", I can't invite you to dinner")
print("Sorry, "+guests.pop()+", I can't invite you to dinner")
print("Sorry, "+guests.pop()+", I can't invite you to dinner")
print("sorry, "+guests.pop()+", I cna't invite you to dinner")
print(guests[0]+", I still invite you to dinner")
print(guests[1]+", I still invite you to dinner")
del guests[0]
del guests[0]
print(guests)